default_settings: null
behaviors:
  BotControllerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      #gail:
      #  gamma: 0.99
      #  strength: 0.9
      #  demo_path: C:\Users\Yaroslav\Documents\Unity Projects\Race (URP)\Assets\Demonstration\DemonstrationDem.demo
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 500000000
    time_horizon: 64
    summary_freq: 50000
    self_play: null
    behavioral_cloning:
      demo_path: C:\Users\Yaroslav\Documents\Unity Projects\Race (URP)\Assets\Demonstration\DemonstrationDem.demo
      strength: 0.5
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
checkpoint_settings:
  run_id: CarAI
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
debug: false